pool:
  vmImage: 'windows-2019'

name: $(SourceBranchName)+1.$(Date:yyyy.MM)$(Rev:.r)

variables:
  disable.coverage.autogenerate: 'true'

steps:
- script: echo Starting build pipeline!
  displayName: 'Hello from Albanian Xrm'

- powershell: |
    echo "##vso[task.setvariable variable=configuration;isOutput=true]$(IF($env:BRANCH -eq "refs/heads/main"){"Azure Pipelines"}else{"release"})"
    echo "##vso[task.setvariable variable=BuildNumber;isOutput=true]$(($env:BuildNumber).Substring(($env:BuildNumber).LastIndexOf('+')+1))"
  name: MyVars
  env: 
    BRANCH: $(Build.SourceBranch)
    BuildNumber: $(Build.BuildNumber)
  displayName: 'Set Configuration Variable'

- task: DownloadSecureFile@1
  name: SignKey 
  inputs:
    secureFile: 'AlbanianXrm.BackgroundWorker.snk'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  
  displayName: 'Secret'

- powershell: echo "##vso[task.setvariable variable=Path;isOutput=true]$((get-item $env:SECURE_FILE).Directory.FullName)"
  name: secretFolder
  env:
    Secure_File: $(SignKey.secureFilePath)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  
  displayName: 'Secret folder'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(secretFolder.Path)
    contents: 'AlbanianXrm.BackgroundWorker.snk' 
    targetFolder: 'AlbanianXrm.BackgroundWorker'
    overWrite: true 
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')  
  displayName: 'Overwrite AlbanianXrm.BackgroundWorker SignKey'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    configuration: $(MyVars.configuration)
    msbuildArguments: '/p:Version=$(MyVars.BuildNumber)'
  displayName: 'Building Solution'

- task: NuGetCommand@2
  displayName: 'Creating NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)/NuGet'
    buildProperties: version=$(MyVars.BuildNumber);configuration=Release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  

- task: PublishBuildArtifacts@1
  displayName: 'Publishing NuGet package to pipeline'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/NuGet'
    artifactName: 'NuGet Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  
      
    